name: cmake-demo CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: make
      run: |
        cd cmake_demo/build-script
        chmod +x build.sh
        ./build.sh
        cd ../bin && ./testcmake